/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "connected": {                                   "en": "connected",                                       "de": "verbunden",                                       "ru": "успешно",                                         "pt": "connected",                                       "nl": "connected",                                       "fr": "connected",                                       "it": "connected",                                       "es": "connected",                                       "pl": "connected",                                       "zh-cn": "连接的"},
    "Output for call_established:": {                "en": "Output for call_established",                     "de": "Ausgabe für call_established",                    "ru": "Вывод для call_established",                      "pt": "Saída para call_established",                     "nl": "Uitvoer voor call_established",                   "fr": "Sortie pour call_established",                    "it": "Uscita per call_established",                     "es": "Salida para call_establecido",                    "pl": "Dane wyjściowe dla call_established",             "zh-cn": "输出为call_builted"},
    "Output for call_closed:": {                     "en": "Output for call_closed",                          "de": "Ausgabe für call_closed",                         "ru": "Выход для call_closed",                           "pt": "Saída para call_closed",                          "nl": "Uitgang voor call_closed",                        "fr": "Sortie pour call_closed",                         "it": "Uscita per call_closed",                          "es": "Salida para call_closed",                         "pl": "Dane wyjściowe dla call_closed",                  "zh-cn": "输出为call_closed"},
    "Output for call_active:": {                     "en": "Output for call_active",                          "de": "Ausgabe für call_active",                         "ru": "Выход для call_active",                           "pt": "Saída para call_active",                          "nl": "Uitgang voor call_active",                        "fr": "Sortie pour call_active",                         "it": "Uscita per call_active",                          "es": "Salida para call_active",                         "pl": "Dane wyjściowe dla call_active",                  "zh-cn": "输出为call_active"},
    "state settings": {                              "en": "state settings",                                  "de": "Statuseinstellungen",                             "ru": "настройки состояния",                             "pt": "configurações de estado",                         "nl": "staat instellingen",                              "fr": "paramètres d'état",                               "it": "impostazioni dello stato",                        "es": "configuraciones de estado",                       "pl": "ustawienia stanu",                                "zh-cn": "状态设定"},
    "CONNECTION": {                                  "en": "CONNECTION",                                      "de": "VERBINDUNG",                                      "ru": "ПОДКЛЮЧЕНИЕ",                                     "pt": "CONEXÃO",                                         "nl": "VERBINDING",                                      "fr": "CONNEXION",                                       "it": "CONNESSIONE",                                     "es": "CONEXIÓN",                                        "pl": "POŁĄCZENIE",                                      "zh-cn": "连接"},
};